"""add node_settings table

Revision ID: 08ded609c40a
Revises: add89462ccd0
Create Date: 2026-02-18 23:11:32.338293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ded609c40a'
down_revision: Union[str, None] = '008_add_mac_address'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('label_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_type', 'node_id', name='_node_setting_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_setting')
    # ### end Alembic commands ###
